class DataError(Exception):
    pass


class NoDataError(DataError):
    pass
